### ISSUE TITLE
Update documentation on libs usage in config.yml

### ISSUE THREAD

**Issue by ghost** [jbrunton/gflows#180]
Thanks a lot for a great tool! 

In the [documentation](https://github.com/jbrunton/gflows/wiki/Templates#ytt-library-files), the yml for "libs" property should be 
```
templates: 
  defaults: 
    libs:
    - my-lib
```
Now it is missing the "defaults" field. 
We can find the [proper example in tests](https://github.com/jbrunton/gflows/blob/4ceb59dd427281520ccb75a587720a3f412748fd/config/gflows_config_test.go#L14).
      
Don't know how to raise a PR for wiki, sorry for that.

**Comment by jbrunton** [comment]
@andrey-covergo: Thanks very much for the heads up! I will make the change and double check the docs.

**Comment by jbrunton** [comment]
I updated the docs. Thanks for the issue!

**Comment by ghost** [comment]
Thanks a lot @jbrunton! 

I was surprised by the quality of your tool, it just works after you understand how to use it. 
You can peek at how we [use it](https://github.com/CoverGo/gflows). Can we use private repositories for GFlows packages?

**Comment by jbrunton** [comment]
@andrey-covergo: thanks for the feedback! It would be very useful to support private repos for packages. I opened #185 with some thoughts on how this could work. Could you take a look and let me know what you think?

EDIT: actually, I realize I need to think through this case a little further (as there are a few different use cases: local; CI using the setup-gflows action; possibly CI without using setup-gflows). I'll try to outline a more thorough proposal later today.

EDIT 2: OK, drafted a proposal which I'm happy with. Feedback welcome.
