### ISSUE TITLE
Thank you on behalf of CoverGo

### ISSUE THREAD

**Issue by ghost** [jbrunton/gflows#197]
Thank you a lot for the gflows project, @jbrunton! 
[CoverGo](https://covergo.com) uses it for GitHub-centric CI and it works like a charm. 
Let me know if I can buy a coffee for you. 

Sorry for the offtopic.

**Comment by jbrunton** [comment]
Glad you're finding it useful, @andrey-covergo! Don't worry about the coffee, but lmk if you have any further suggestions for the repo!
